language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - build-tools-24.0.1
    - android-24
    - platform-tools
    - extra-android-m2repository
    - extra-android-support

script:
  - ./gradlew build

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false